<?php
namespace Iayoo\OpenApi\Lumen;
use Laravel\Lumen\Providers\EventServiceProvider as ServiceProvider;

class Provider extends ServiceProvider
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}